"""empty message

Revision ID: c48f63e222d7
Revises: 147f35b5d606
Create Date: 2021-11-23 19:28:02.699919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c48f63e222d7'
down_revision = '147f35b5d606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intents',
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('intent', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intents')
    # ### end Alembic commands ###
